//const Person = require('./person')
// const person = new Person('mau')
// require('./modules/path')
// require('./modules/fs')
// require('./modules/http')
//require('./modules/express')
require("dotenv").config()
const coneectToDatabase = require('./src/database/connect')

coneectToDatabase()